# this files contains utility data for the pendu.py file

SCORES_FILE_NAME = "scores"

MAX_TRIES = 8

word_list = [
    "roquette",
    "paravent",
    "coquette",
    "immondes",
    "colombin",
    "langages",
    "archiduc",
    "informes",
    "torturer",
    "toscanes",
    "distants",
    "égoutter",
    "charogne",
    "annuelle",
    "vaisseau",
    "spatules",
    "grillade",
    "gazoducs",
    "citation",
    "antilope",
    "omission",
    "valkyrie",
    "immigrer",
    "anecdote",
    "merisier",
    "osseuses",
    "rengaine",
    "chasseur",
    "indiquer",
    "coteries",
    "colorant",
    "veilleur",
    "babiller",
    "stations",
    "asphalte",
    "palabrer",
    "insister",
    "perruque",
    "exposant",
    "empoigne",
    "traqueur",
    "carbones",
    "terminer",
    "effilage",
    "national",
    "oratrice",
    "rondache",
    "casernes",
    "paysanne"
]